[[redirects]]
from = "/api/*"
to = "https://api.openweathermap.org/data/2.5/group:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "build"
command = "CI= npm run build"